version: '3'

services:
    web:
        image: php:7.4-apache
        container_name: streetmap_webserver_php_apache
        restart: always
        ports:
            - 80:80     
        volumes:
            - "./client:/var/www/html/app"

    jsonserver:
        image: clue/json-server
        container_name: streetmap_json_server
        restart: always
        ports:
            - 8083:80
        volumes:
            - ./jsonServer:/data